title: "Accelerated Mod 0 Site - Turing School of Software and Design"
description: "Open source curriculum for the Turing School of Software and Design's Accelerated Mod 0."
url: "//turingschool.github.io/accelerated-mod-0/"


baseurl: ''
permalink: /:title

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude: [
  'Gemfile',
  'Gemfile.lock',
  'README.md',
  'LICENSE',
  'CNAME'
]

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"

assets:
  root_url: '/assets'

images:
  root_url: '/assets/images'

plugins:
  - jemoji
